### ISSUE TITLE
[B/E] 백엔드 프로젝트 빌드업

### ISSUE THREAD

**Issue by HyunGyu-Lee** [Team-HST/nklcb#2]
## 기술스택
- Spring Boot 2.5.3 with Gradle
- Java11
- JPA
- Spring Batch
- MySQL

## 프로젝트 구성
- nklcb-be
  - nklcb-core
    - 타 프로젝트에서 사용될 엔티티 / 레파지토리를 포함한 프로젝트 공통사항 정의 
  - nklcb-batch
    - 채용정보를 수집 / 가공해 DB에 적재하는 배치작업 담당
  - nklcb-api
    - DB에 적재된 채용정보를 조회하는 서비스 API 제공 담당 

## TODO 
- [x] 프로젝트 생성 & 기본 설정
- [x] 프로젝트별 설정
  - [x] nklcb-core 프로젝트 설정 (lib)
  - [x] nklcb-batch 프로젝트 설정
  - [x] nklcb-api 프로젝트 설정
